// This file was automatically generated by ctpgen
#ifndef {{.HeaderOnce}}
#define {{.HeaderOnce}}
#include <stdint.h>
#include "{{.src}}"
class {{.className}} : public {{.name}}
{
public:
  {{.className}}(uint64_t ptr);
  virtual ~{{.className}}();
{{range $method := .methods}}
  virtual void {{$method.Name}}(
{{- $lenArg := len $method.Args -}}
{{- range $i, $arg := $method.Args}}
{{- if ne $i 0 -}}
,
{{- end -}}
{{- $arg.Type}} {{$arg.Name}}
{{- end -}});
{{end}}

private:
  uint64_t ptr = 0;
};
#endif  // {{.HeaderOnce}}