// This file was automatically generated by ctpgen
#ifndef {{.HeaderOnce}}
#define {{.HeaderOnce}}
#include <stdlib.h>
#include "{{.src}}"
typedef enum THOST_TE_RESUME_TYPE THOST_TE_RESUME_TYPE;

{{range $struct := .structs}}
typedef struct {{$struct.Name}} {{$struct.Name}};
{{- end }}


#endif  // {{.HeaderOnce}}
